---
include:
# - board: eyelash_sofle_left
#    shield: nice_view
#  - board: eyelash_sofle_right
#    shield: nice_view_custom
#  - board: eyelash_sofle_left
#    shield: nice_view
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
#    artifact-name: eyelash_sofle_studio_left
#  - board: eyelash_sofle_left
#    shield: settings_reset
  - board: nice_nano_v2
    shield: eyelash_sofle_left nice_view_adapter nice_view_gem
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: eyelash_sofle_right nice_view_adapter nice_view_gem
    snippet: zmk-usb-logging
    extra_modules:
      - ../kb_zmk_ps2_mouse_trackpoint_driver
  - board: nice_nano_v2
    shield: settings_reset
